<?php
define('ROOT_DIRECTORY', realpath(dirname(__FILE__) . '/..'));
define('BASE_DIR', '/');
define('BASE_URL', 'http://localhost');
define('VIEW_URL', BASE_URL . '/views/');
define('APP_URL', BASE_URL . '/app/');
define('STATIC_URL', BASE_URL . '/static/');
define('IMAGES_URL', STATIC_URL . 'img/');
define('MODEL_URL', BASE_URL . '/model/');
define('TEMPLATES_URL', BASE_URL . '/templates/');
define('PLUGINS_URL', BASE_URL . '/plugins/');
define('CONTACT', 'about_us');
define('HOME', '');
define('USERS', 'users');
define('POSTS', 'posts');
define('ROLES', 'roles');
define('LOGIN', 'login');
define('PROFILE', USERS . '/profile');
define('CREATE_USER', USERS . '/create');
define('GET_POST', POSTS . '/get');
define('CREATE_POST', POSTS . '/create');
define('UPDATE_POST', POSTS . '/update');
define('PAGE', 'page');
define('GALLERY', 'image_gallery');
define('GET_IMAGE', GALLERY . '/get');
define('SEARCH', 'home/search');
define('CONTACT_SEO_URL', BASE_URL . '/' . CONTACT);
define('HOME_SEO_URL', BASE_URL . '/' . HOME);
define('PROFILE_SEO_URL', BASE_URL . '/' . PROFILE);
define('USERS_SEO_URL', BASE_URL . '/' . USERS);
define('POST_SEO_URL', BASE_URL . '/' . GET_POST);
define('POSTS_SEO_URL', BASE_URL . '/' . POSTS);
define('ROLES_SEO_URL', BASE_URL . '/' . ROLES);
define('LOGIN_SEO_URL', BASE_URL . '/' . LOGIN);
define('CREATE_POST_SEO_URL', BASE_URL . '/' . CREATE_POST);
define('CREATE_USER_SEO_URL', BASE_URL . '/' . CREATE_USER);
define('UPDATE_POST_SEO_URL', BASE_URL . '/' . UPDATE_POST);
define('GALLERY_SEO_URL', BASE_URL . '/' . GALLERY);
define('IMAGE_SEO_URL', BASE_URL . '/' . GALLERY);
define('SEARCH_POST_SEO_URL', BASE_URL . '/' . SEARCH);
define('VIEWS_PATH', ROOT_DIRECTORY . '/views/');
define('APP_PATH', ROOT_DIRECTORY . '/app/');
define('STATIC_PATH', ROOT_DIRECTORY . '/static/');
define('IMAGES_PATH', STATIC_PATH . 'img/');
define('TEMPLATES_PATH', ROOT_DIRECTORY . '/templates/');
define('MODELS_PATH', ROOT_DIRECTORY . '/models/');
define('DAO_PATH', MODELS_PATH . 'dao/');
define('LIBS_PATH', ROOT_DIRECTORY . '/libs/');
define('CORE_PATH', LIBS_PATH . 'core/');
define('CONTROLLERS_PATH', ROOT_DIRECTORY . '/controllers/');
define('ERROR_LOG_PATH', ROOT_DIRECTORY . '/php-error.log');
define('DB_TYPE', 'mysql');
define('DB_HOST', 'localhost');
define('DB_USER', 'root');
define('DB_PASSWORD', '');
define('DB_NAME', 'fictionplanetdb_test');
define('DB_CHARSET', 'utf8mb4');
define('APP_DEBUG', true);
define('ROOT', 1);
define('REGISTERED_USER', 4);
define('UPLOAD_POSTS_DIR', '/uploads/posts/attachments/');
define('UPLOAD_IMG_EDITOR_DIR', '/uploads/editor/img/');
define('UPLOAD_IMG_GALLERY_DIR', '/uploads/gallery/');
define('UPLOAD_IMG_GALLERY_URL', BASE_URL . '/uploads/gallery/');
define('MDL_USERS', 1);
define('MDL_ROLES', 2);
define('MDL_POSTS', 3);
define('MDL_PUBLIC_CALENDAR', 4);
define('MDL_PUBL_DATA', 5);
define('MDL_PRSN_DATA', 6);
define('MDL_CHAT', 7);
define('MDL_IMAGES', 8);

require_once CORE_PATH . 'Connection.php';
require_once CORE_PATH . 'AppException.php';
require_once CORE_PATH . 'Controller.php';
require_once CORE_PATH . 'View.php';
require_once CORE_PATH . 'Redirection.php';
require_once CORE_PATH . 'Utilities.php';
require_once LIBS_PATH . 'Session.php';
require_once LIBS_PATH . 'Pager.php';
require_once MODELS_PATH . 'UserModel.php';
require_once MODELS_PATH . 'RoleModel.php';
require_once MODELS_PATH . 'PermissionModel.php';
require_once MODELS_PATH . 'PostModel.php';
require_once MODELS_PATH . 'ChatMessageModel.php';
require_once MODELS_PATH . 'ContactModel.php';
require_once MODELS_PATH . 'FriendRequestsModel.php';
require_once MODELS_PATH . 'ImageGalleryModel.php';
require_once MODELS_PATH . 'CalendarEventModel.php';
require_once MODELS_PATH . 'ModuleModel.php';
require_once DAO_PATH . 'UserDAO.php';
require_once DAO_PATH . 'RoleDAO.php';
require_once DAO_PATH . 'PermissionDAO.php';
require_once DAO_PATH . 'PostDAO.php';
require_once DAO_PATH . 'ChatMessageDAO.php';
require_once DAO_PATH . 'ContactDAO.php';
require_once DAO_PATH . 'FriendRequestsDAO.php';
require_once DAO_PATH . 'ImageGalleryDAO.php';
require_once DAO_PATH . 'CalendarEventsDAO.php';
require_once DAO_PATH . 'ModuleDAO.php';
require_once LIBS_PATH . 'validators/LoginValidator.php';
require_once LIBS_PATH . 'validators/NewUserValidator.php';
require_once LIBS_PATH . 'validators/NewPostsValidator.php';
require_once LIBS_PATH . 'validators/UpdatedPostsValidator.php';
